module.exports = {
    ON_LOADING:'ON_LOADING',
    OFF_LOADING:'OFF_LOADING',
    OPEN_SEARCH:'OPEN_SEARCH',
    CLOSE_SEARCH:'CLOSE_SEARCH',
    REMOVE_CLIENT:'REMOVE_CLIENT',
    CHANGE_PASSWORD:'CHANGE_PASSWORD',
    CHANGE_SEARCH_DATA:'CHANGE_SEARCH_DATA',
    CHANGE_SELECTED_CUSTOMER:'CHANGE_SELECTED_CLIENT',
    CHANGE_REQUIRE_PASSWORD:'CHANGE_REQUIRE_PASSWORD',
    CLOSE_REQUIRED_PASSWORD: 'CLOSE_REQUIRED_PASSWORD'
}