module.exports = {
    ON_LOADING:'ON_LOADING',
    OFF_LOADING:'OFF_LOADING',
    OPEN_SEARCH:'OPEN_SEARCH',
    CLOSE_SEARCH:'CLOSE_SEARCH',
    REMOVE_JOB:'REMOVE_JOB',
    CHANGE_PASSWORD:'CHANGE_PASSWORD',
    CHANGE_SEARCH_DATA:'CHANGE_SEARCH_DATA',
    CHANGE_SELECTED_JOB:'CHANGE_SELECTED_JOB',
    CHANGE_REQUIRE_PASSWORD:'CHANGE_REQUIRE_PASSWORD',
    CLOSE_REQUIRED_PASSWORD: 'CLOSE_REQUIRED_PASSWORD',
    CHANGE_VIEW_JOB:'CHANGE_VIEW_JOB'
}