module.exports={
    ADD_SELECTED_USER:'ADD_SELECTED_USER',
    CHANGE_REQUIRE_PASSWORD:'CHANGE_REQUIRE_PASSWORD',
    CHANGE_PASSWORD:'CHANGE_PASSWORD',
    CLOSE_REQUIRE_PASSWORD:'CLOSE_REQUIRE_PASSWORD',
    CHANGE_USERS_STATE:'CHANGE_USERS_STATE',
    CLEAR_SELECTED_USER:"CLEAR_SELECTED_USER"
}